# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Make sure cocotb libraries installed in a venv can be found.
PYTHONPATH = $(shell cocotb-config --prefix)
export PYTHONPATH

# Configuration for cocotb.
SIM ?= icarus
TOPLEVEL_LANG = verilog

include $(shell cocotb-config --makefiles)/Makefile.sim
