# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Configuration for cocotb.
VERILOG_SOURCES = \
	../../mem.v \
	../../mem_control.v
TOPLEVEL = mem_control
MODULE = test_mem_control

include ../Makefile.common
