# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Configuration for cocotb.
VERILOG_SOURCES = \
	../../alu.v \
	../../control.v \
	../../cpu.v \
	../../fifo_if.v \
	../../mem.v \
	../../mem_control.v \
	../../registers.v
TOPLEVEL = cpu
MODULE = test_cpu

include ../Makefile.common
