# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Configuration for cocotb.
VERILOG_SOURCES = ../../mem_data.v
TOPLEVEL = mem_data
MODULE = test_mem

include ../Makefile.common
