# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Configuration for cocotb.
VERILOG_SOURCES = ../../registers.v
TOPLEVEL = registers
MODULE = test_registers

include ../Makefile.common
