# Copyright (C) 2023 Petr Pavlu <petr.pavlu@dagobah.cz>
# SPDX-License-Identifier: MIT

# Configuration for cocotb.
VERILOG_SOURCES = ../../alu.v
TOPLEVEL = alu
MODULE = test_alu

include ../Makefile.common
